client: Added a Dockerimage
paritytech/substrate-matrix-faucet pull request #238
Opened 2023-03-20 10:59 UTC by Bullrich

Added a docker image for the client, in the case that we want to deploy the site to any other platform aside from GitHub Pages

2023-03-20 11:01 UTC, rzadp approved these changes

2023-03-20 11:17 UTC, PierreBesson requested changes
There should be a CI job that pushes this image to `paritytech/faucet-ui` with the same tags as the backend.

2023-03-20 11:17 UTC, PierreBesson commented on client/Dockerfile
> +ARG CAPTCHA_KEY
Those variables should not be set in docker build args but by docker environment variables. If those environment specific variables are set in the docker image itself, the image will not longer be portable to multiple environments without rebuilding.

2023-03-21 14:50 UTC, PierreBesson submitted a review, later dismissed

2023-03-24 09:45 UTC, Bullrich commented
Hi @PierreBesson! I added the logic to build the image and publish it in `gitlab-ci`.

Could you please review that file and let me know if it is as intended? I'm afraid my knowledge of gitlab's deployment script is not very broad

2023-03-24 12:29 UTC, rzadp commented
Should we update `publish-docker-image-description` as well?

2023-03-24 20:04 UTC, mordamax approved these changes

2023-03-27 08:44 UTC, sergejparity commented
> Should we update `publish-docker-image-description` as well?

Yes, this make sense. I'll add the commit for that.

2023-03-27 08:46 UTC, sergejparity approved these changes

2023-03-27 08:59 UTC, merged