Wk add web3 privileged
paritytech/substrate-matrix-faucet pull request #81
Opened 2021-10-01 09:32 UTC by chevdor

2021-10-01 10:19 UTC, AndreiEres requested changes

2021-10-01 10:19 UTC, AndreiEres commented on src/server/index.ts
> +      const privileged = sender.endsWith(':matrix.parity.io') || sender.endsWith(':web3.foundation');
`isPrivileged` for consistency?

2021-10-04 13:10 UTC, chevdor commented on src/server/index.ts
> +      const privileged = sender.endsWith(':matrix.parity.io') || sender.endsWith(':web3.foundation');
Fixed

2021-10-05 08:20 UTC, AndreiEres approved these changes

2021-10-05 08:47 UTC, merged